Virtual_assistant_webapp/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_view, name='home'),
    path("register", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path("logout", views.logout_request, name= "logout"),
    path('accounts/', include('allauth.urls')),
    path("account", views.account_view, name="account"),
    path("dashboard", views.dashboard_view, name="dashboard"),
    path('meetings/', include('meetings.urls', 'meetings')),
    path('must_athenticate/', views.must_athenticate_view, name="must_authenticate"),

    #REST FRAMEWORK URLS
    path('api/meetings/', include('meetings.api.urls', 'meetings_api')),
    path('api/account/', include('users.api.urls', 'accounts_api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meetings/api/urls.py
from meetings.api.views import (
    api_detail_meeting_view,
    api_delete_meeting_view,
    api_update_meeting_view,
    api_create_meeting_view,
    ApiMeetingView
)

from django.urls import path

app_name = "meetings"

urlpatterns = [
    path('<slug>/', api_detail_meeting_view, name="detail"),
    path('<slug>/update', api_update_meeting_view, name="update"),
    path('<slug>/delete', api_delete_meeting_view, name="delete"),
    path('create', api_create_meeting_view, name="create"),
    path('list', ApiMeetingView.as_view(), name="list"),


]

meetings/urls.py
from django.urls import path
from meetings.views import(
    create_meeting_view,
    detail_meeting_view,
    edit_meeting_view
)

app_name = 'meetings'

urlpatterns = [
    path('create/', create_meeting_view, name="create"),
    path('<slug>/', detail_meeting_view, name="detail"),
    path('<slug>/edit', edit_meeting_view, name="edit"),
]

meetings/models.py
from django.db import models

from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver

class Meeting(models.Model):
    location = models.CharField(max_length=120)
    participating_users = models.CharField(max_length=120)  #To be completed
    time = models.DateTimeField()
    activity = models.CharField(max_length=120)
    active = models.BooleanField()
    is_private = models.BooleanField()
# Create your models here.

def upload_location(instance, filename, *args, **kwargs):
    file_path = 'meeting/{creator_id}/{title}-{filename}'.format(
        creator_id = str(instance.creator.id), title=str(instance.title), filename = filename
    )
    return file_path

class MeetingPost(models.Model):
    title = models.CharField(max_length=50, null=False, blank=False)
    image = models.ImageField(upload_to=upload_location, null=False, blank=False)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, unique=True)
    location = models.CharField(max_length=120)
    time = models.DateTimeField()
    activity = models.CharField(max_length=120)
    active = models.BooleanField(null=True, blank=True)
    is_private = models.BooleanField(null=True, blank=True)

    def __str__(self):
        return self.title

@receiver(post_delete, sender=MeetingPost)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)

def pre_save_meeting_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.creator.username + "-" + instance.title)

pre_save.connect(pre_save_meeting_post_receiver, sender=MeetingPost)

meetings/forms.py
from django import forms 
from meetings.models import MeetingPost

class CreateMeetingForm(forms.ModelForm):

    class Meta:
        model = MeetingPost
        fields = [
            'title',
            'image',
            'location',
            'time',
            'activity'
        ]

class UpdateMeetingPostForm(forms.ModelForm):

    class Meta:
        model = MeetingPost
        fields = ['title', 'image', 'location', 'time', 'activity']

        def save(self, commit=True):
            meeting_post = self.instance
            meeting_post.title = self.cleaned_data['title']
            meeting_post.location = self.cleaned_data['location']
            meeting_post.time = self.cleaned_data['time']
            meeting_post.activity = self.cleaned_data['activity']     

            if self.cleaned_data['image']:
                meeting_post.image = self.cleaned_data['image']

            if commit:
                meeting_post.save()
            return meeting_post()   

meetings/api/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.pagination import PageNumberPagination
from rest_framework.generics import ListAPIView
from rest_framework.authentication import TokenAuthentication
from rest_framework.filters import SearchFilter, OrderingFilter

from users.models import Account
from meetings.models import MeetingPost
from meetings.api.serializers import MeetingPostSerializer

@api_view(['GET', ])
@permission_classes((IsAuthenticated,))
def api_detail_meeting_view(request, slug):
    try:
        meeting_post = MeetingPost.objects.get(slug=slug)
    except MeetingPost.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == "GET":
        serializer = MeetingPostSerializer(meeting_post)
        return Response(serializer.data)

@api_view(['PUT', ])
@permission_classes((IsAuthenticated,))
def api_update_meeting_view(request, slug):
    try:
        meeting_post = MeetingPost.objects.get(slug=slug)
    except MeetingPost.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    user = request.user
    if meeting_post.author != user:
        return Response({'response': "You don't have permission to edit that."})

    if request.method == "PUT":
        serializer = MeetingPostSerializer(meeting_post, data=request.data)
        data= {}
        if serializer.is_valid():
            serializer.save()
            data["success"] = "update successful"
            return Response(data=data)
        return Response(serializer.errors, status=status.HTTP_404_BAD_REQUEST)

@api_view(['DELETE', ])
@permission_classes((IsAuthenticated,))
def api_delete_meeting_view(request, slug):
    try:
        meeting_post = MeetingPost.objects.get(slug=slug)
    except MeetingPost.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    user = request.user
    if meeting_post.author != user:
        return Response({'response': "You don't have permission to delete that."})

    if request.method == "DELETE":
        operation= meeting_post.delete()
        data = {}
        if operation:
            data["success"] = "delete successful"
        else:
            data["failure"] = "delete failed"
        return Response(data=data)

@api_view(['POST', ])
@permission_classes((IsAuthenticated,))
def api_create_meeting_view(request):
    account = request.user

    meeting_post = MeetingPost(creator=account)

    if request.method == "POST":
        serializer = MeetingPostSerializer(meeting_post, data=request.data)
        data = {}
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class ApiMeetingView(ListAPIView):
    queryset = MeetingPost.objects.all()
    serializer_class = MeetingPostSerializer
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)
    pagination_class = PageNumberPagination
    filter_backends = (SearchFilter, OrderingFilter)
    search_fields = ('title', 'location', 'time', 'activity', 'creator__username')

meetings/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.http import HttpResponse

from meetings.models import MeetingPost
from meetings.forms import CreateMeetingForm, UpdateMeetingPostForm
from users.models import Account

def create_meeting_view(request):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')

    form = CreateMeetingForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        creator = Account.objects.filter(email=user.email).first()
        obj.creator = creator
        obj.save()
        form = CreateMeetingForm()

    context['form'] = form

    return render(request, "meetings/create_meeting.html", {})

def detail_meeting_view(request, slug):

    context = {}

    meeting_post = get_object_or_404(MeetingPost, slug=slug)
    context['meeting_post'] = meeting_post

    return render(request, 'meetings/detail_meeting.html', context)

def edit_meeting_view(request, slug):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect("must_authenticate")

    meeting_post = get_object_or_404(MeetingPost, slug=slug)
    
    if meeting_post.creator != user:
        return HttpResponse("You are not the creator of that meeting.")
    
    if request.POST:
        form = UpdateMeetingPostForm(request.POST or None, request.FILES or None, instance=meeting_post)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            context['success_message'] = 'Updated'
            meeting_post = obj
    form = UpdateMeetingPostForm(
        initial= {
            "title": meeting_post.title,
            "location": meeting_post.location,
            "time": meeting_post.time,
            "activity": meeting_post.activity,
            "image": meeting_post.image,
        }
    )
    
    context['form'] = form
    return render(request, 'meetings/edit_meeting.html', context)

def get_meeting_queryset(query=None):
    queryset = []
    queries = query.split(" ")
    for q in queries:
        posts = MeetingPost.objects.filter(
            Q(title__icontains=q)|
            Q(location__icontains=q)|
            Q(time__icontains=q)|
            Q(activity__icontains=q)
        ).distinct()

        for post in posts:
            queryset.append(post)

    return list(set(queryset))

meetings/templates/meetings/snippets/meeting_post_pagination.html
<!-- FILTERED Pagination -->
<style>
.example .pagination>li>a,
.example .pagination>li>span {
  border: 1px solid #ef4639;
}
.pagination>li.active>a {
  background: #ef4639;
  color: #fff;
}
</style>
<div class="d-flex flex-column m-auto pagination mt-5">
    <nav aria-label="Page navigation">
    <ul class="pagination pg-grey justify-content-center">
        {% if meeting_posts.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ meeting_posts.previous_page_number }}">&laquo; Previous</a>
            </li>
        {% endif %}
    
        {% for i in meeting_posts.paginator.page_range %}
            {% if meeting_posts.number == i %}
                <li class="page-item active"><a class="page-link">{{ i }}</a></li>
            {% else %}
                <li class="page-item" ><a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        
        {% if meeting_posts.has_next %}
            <li class="page-item page-item">
              <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ meeting_posts.next_page_number }}">Next</a>
            </li>
            <li class="page-item">
              <a class="page-link"  href="?{% if query %}q={{query}}&{% endif %}page={{ meeting_posts.paginator.num_pages }}">Last &raquo;</a>
            </li>
        {% endif %}
    </ul>
    </nav>
    </div>
    <!-- end pagination-->

meetings/templates/meetings/snippets/meeting_post_snippet.html
<style type="text/css">
	.card{
		max-width: 700px;
        width: 100%;
	}
	.card-body{
		padding: 20px;
	}
	.card-title{
		color: #ef4639;
	}
</style>

{% if meeting_posts %}
<div class="container">
	<div class="row">
		<!-- Blog Post -->
		<div class="card m-auto">
			<a href="{% url 'meetings:detail' post.slug %}">
				<img class="card-img-top mt-3" src="{{meeting_posts.image.url}}">
			</a>
			
			<div class="card-body mt-2 mb-2">
				<a style="color: #ef4639;" href="{% url 'meetings:detail' post.slug %}">
					<h2 class="card-title">{{meeting_posts.title}}</h2>
				</a>
				<p class="card-text">{{meeting_posts.location|truncatechars:180}}</p>
				{% if meeting_posts.creator == request.user %}
					<a href="{% url 'meetings:edit' post.slug %}" class="btn btn-danger">Update</a>
				{% endif %}
			</div>
			<div class="card-footer text-muted">
			  Updated on by {{meeting_posts.creator}}
			</div>
		</div>
	</div>
</div>
{% else %}

<div class="container">
    <div class="row">
        <div class="card m-auto">
            <div class="card-body mt-2 mb-2">
                <h2 class="card-title">
                    No results
                </h2>
                <p class="card-text">There were no results matching your search: "{{query}}".</p>
            </div>
        </div>
    </div>
</div>

{% endif %}