Virtual_assistant_webapp/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_view, name='home'),
    path("register", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path("logout", views.logout_request, name= "logout"),
    path('accounts/', include('allauth.urls')),
    path("account", views.account_view, name="account"),
    path("dashboard", views.dashboard_view, name="dashboard"),
    path('meetings/', include('meetings.urls', 'meetings')),
    path('must_athenticate/', views.must_athenticate_view, name="must_authenticate"),

    #REST FRAMEWORK URLS
    path('api/meetings/', include('meetings.api.urls', 'meetings_api')),
    path('api/account/', include('users.api.urls', 'accounts_api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meetings/urls.py
from django.urls import path
from meetings.views import(
    create_meeting_view,
    detail_meeting_view,
    edit_meeting_view
)

app_name = 'meetings'

urlpatterns = [
    path('create/', create_meeting_view, name="create"),
    path('<slug>/', detail_meeting_view, name="detail"),
    path('<slug>/edit', edit_meeting_view, name="edit"),
]

templates/account.html
{% extends "base.html" %} {% block content %} {% load crispy_forms_tags %}

<style type="text/css">
	.form-signin {
	width: 100%;
	max-width: 330px;
	padding: 15px;
	margin: 0 auto;
	}
	.form-signin .form-control {
	position: relative;
	box-sizing: border-box;
	height: auto;
	padding: 10px;
	font-size: 16px;
	}
	.form-signin .form-control:focus {
	z-index: 2;
	}
	.form-signin input[type="email"] {
	margin-bottom: 10px;
	border-bottom-right-radius: 0;
	border-bottom-left-radius: 0;
	}
	.form-signin input[type="username"] {
	margin-bottom: 10px;
	border-top-left-radius: 0;
	border-top-right-radius: 0;
	}
	.h3{
		text-align: center;
	}
	.meeting-posts{
		max-width: 500px;
		width: 100%;
		margin: auto;
	}
</style>

<form class="form-signin" method="post">{% csrf_token %}
	<div class="d-flex flex-column pb-3">
		<img class="img-fluid mx-auto d-block" src="https://i.ibb.co/s54bdnz/Elder-Aid-Logo-1.png" alt="Elder-Aid-Logo" width="72" height="72">
	</div>
	<h1 class="h3 mb-3 font-weight-normal">Account</h1>
	<label for="inputEmail" class="sr-only">Email address</label>
	<input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus value="{{account_form.initial.email}}">
	<label for="inputUsername" class="sr-only">Username</label>
	<input type="text" name="username" id="inputUsername" class="form-control" placeholder="Username" required value="{{account_form.initial.username}}">

	{% for field in account_form %}
		{% for error in field.errors %}
			<p style="color: red">{{ error }}</p>
		{% endfor %}
	{% endfor %}

	{% if account_form.non_field_errors %}
		<div style="color:red "><p>{{ account_form.non_field_errors }}</p></div>
	{% endif %}

	{% if success_message %}
		<p style="color:green; text-align: center;">{{success_message}}</p>
	{% endif %}
	<div class="d-flex justify-content-center mt-3">
		<button class="btn btn-lg btn-danger btn-block" type="submit">Save Changes</button>
	</div>
  </form>

<div class="container mt-4 p-4">
	<div class="row">
		<div class="meeting-posts">
			<h3 class="mb-3 font-weight-normal">Meeting Posts:</h3>
			{% if meeting_posts %}
			<ul class="list-group">
				{% for post in meeting_posts %}
				<a href="{% url 'meetings:detail' post.slug %}" style="text-decoration: none">
					<li class="list-group-item">{{post}}</li>
				</a>
				{% endfor %}
			</ul>
			{% else %}
			<p>You have no meeting posts. Create a meeting <a href="{% url 'meetings:create' %}"></a></p>
			{% endif %}
		</div>
	</div>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Virtual Assistant for the Elderly</title>
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
	</head>
	<body>
		{% include 'navbar.html' %} {% include 'base_css.html' %} 
		<style type="text/css">
			.main{
				min-height: 100vh;
				height: 100%;
			}
		</style>
		<div class="main">
			{% block content %}
		
			{% endblock content %}
		</div>

		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

templates/base_css.html
<style type="text/css">
    body{
        background-color: #f2f2f2;
    }
</style>

templates/dashboard.html
{% extends 'base.html' %} {% block content %}
<h1>Elder Aid Dashboard</h1>
<label for="inputAccount" class="sr-only">Linked Account</label>
<input type="text" name="account" id="inputAccount" placeholder="Linked Account">
<br>

<li>Last meetings</li>
<li>Last Active</li>

<li>Last Location</li>

{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
<style type="text/css">

	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) { 
		.right-column{
			margin-left: 20px;
		}
	}

	.meeting-post-container{
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}

	.left-column{
		padding:0px;
	}

	.right-column{
		padding:0px;
	}
	.lead{
		font-size: 17px;
	}
</style>
<div class="container">
	<div class="row">

		<!-- blog feed -->
		<div class="left-column col-lg-7 offset-lg-1">


			<div class="d-lg-none mb-3">
				<div class="card m-auto d-flex flex-column p-3">
					<img class="img-fluid d-block m-auto pb-2" src="https://i.ibb.co/s54bdnz/Elder-Aid-Logo-1.png" width="72" height="72">
					<p class="lead">A virtual assistant created to help make technology more accessible for the Elderly</p>
					<p class="m-auto"><a class="btn btn-danger btn-lg" href="{% url 'meetings:create' %}">Create post</a></p>
				</div>
			</div>
            {% if meeting_posts %}
                {% for post in meeting_posts %}
                    <div class="meeting-post-container">
                        {% include 'meetings/snippets/meeting_post_snippet.html' with meeting_posts=post %}
                    </div>
                {% endfor %}
            {% else %}
                <div class="meeting-post-container">
                    {% include 'meetings/snippets/meeting_post_snippet.html' with query=query %}
                </div>
            {% endif %}

		{% include 'meetings/snippets/meeting_post_pagination.html' with meeting_posts=meeting_posts %}
		
		</div>

		<!-- Right 'create post' column  -->
		<div class="right-column col-lg-3 d-lg-flex d-none flex-column">

			<div class="card create-post-bar d-flex flex-column p-3">
				<img class="img-fluid d-block m-auto pb-2" src="https://i.ibb.co/s54bdnz/Elder-Aid-Logo-1.png" width="72" height="72">
				<p class="lead">A virtual assistant created to help make technology more accessible for the Elderly</p>
				<p class="m-auto"><a class="btn btn-danger btn-lg" href="{% url 'meetings:create' %}">Create post</a></p>
			</div>
		
		</div>

	</div>
</div>

{% endblock content %}

templates/login.html
{% extends "base.html" %} {% block content %} {% load crispy_forms_tags %}

<!--Login-->
<style type="text/css">
	.form-signin {
	width: 100%;
	max-width: 330px;
	padding: 15px;
	margin: 0 auto;
	}
	.form-signin .checkbox {
	font-weight: 400;
	}
	.form-signin .form-control {
	position: relative;
	box-sizing: border-box;
	height: auto;
	padding: 10px;
	font-size: 16px;
	}
	.form-signin .form-control:focus {
	z-index: 2;
	}
	.form-signin input[type="email"] {
	margin-bottom: -1px;
	border-bottom-right-radius: 0;
	border-bottom-left-radius: 0;
	}
	.form-signin input[type="password"] {
	margin-bottom: 10px;
	border-top-left-radius: 0;
	border-top-right-radius: 0;
	}
	.h3{
		text-align: center;
	}
</style>

<form class="form-signin" method="post">{% csrf_token %}
	<div class="d-flex flex-column pb-3">
		<img class="img-fluid mx-auto d-block" src="https://i.ibb.co/s54bdnz/Elder-Aid-Logo-1.png" alt="Elder-Aid-Logo" width="72" height="72">
	</div>
	<h1 class="h3 mb-3 font-weight-normal">Login</h1>
	<label for="inputEmail" class="sr-only">Email address</label>
	<input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
	<label for="inputPassword" class="sr-only">Password</label>
	<input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>

	{% for field in form %}
		{% for error in field.errors %}
			<p style="color: red">{{ error }}</p>
		{% endfor %}
	{% endfor %}

	{% if form.non_field_errors %}
		<div style="color:red "><p>{{ form.non_field_errors }}</p></div>
	{% endif %}
	<div class="d-flex justify-content-center">
		<button class="btn btn-lg btn-danger btn-block" type="submit">Login</button>
	</div>
	<div class="d-flex justify-content-center">
		<p class="mt-5 mb-3 text-muted">&copy; MYP Personal Project 2022-2023</p>
	</div>
  </form>


<!-- <div class="container py-5">
	<h1>Login</h1>
	<form method="POST">
		{% csrf_token %} 
		{% for field in form %}
		<p>
			{{ field.label_tag }}
			{{ field }}

			{% if field.label.help_text %}
			<small style="color: gray">{{ field.help_text }}</small>
			{% endif %}

		</p>
		{% endfor %}

		{% for field in form %}
			{% for error in field.errors %}
				<p style="color: red">{{ error }}</p>
			{% endfor %}
		{% endfor %}

		{% if form.non_field_errors %}
			<div style="color:red "><p>{{ form.non_field_errors }}</p></div>
		{% endif %}

		<button class="btn btn-primary" type="submit">Login</button>
	</form>
	<p class="text-center">
		Don't have an account? <a href="/register">Create an account</a>.
	</p>
</div>

{% endblock %} -->

templates/navbar.html
<style type="text/css">
	@media (min-width: 768px) {
	  html {
	    font-size: 16px;
	  }
	}

	.search-bar{
		max-width: 700px;
		width: 100%;
		margin-right: 90px;
	}
	form{
		width: 100%;
	}
</style>

<!-- Header -->
<div class="d-flex flex-column flex-md-row justify-content-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal" style="margin-right: 20px;">
  	{% if request.user.is_authenticated %}
  		<p class="m-auto mt-2">Hello, {{request.user.username}}</p>
  	{% endif %}
  </h5>

	<div class="search-bar sm-2 mr-2">
		<form method="get">
			<input class="form-control" style="height: 50px;" type="text" name="q" id="id_q" placeholder="Search meeting...">
		</form>
	</div>

  <nav class="my-2 my-md-1 mr-md-3">
  	{% if request.user.is_authenticated %}
	  	<a role="button" class="p-2 btn btn-dark btn-lg" href="{% url 'home' %}">Home</a>
	    <a role="button" class="p-2 btn btn-danger btn-lg" href="{% url 'account' %}">Account</a>
	    <a role="button" class="p-2 btn btn-light btn-outline-dark btn-lg" href="{% url 'logout' %}">Logout</a>
	{% else %}
		<a role="button" class="p-2 btn btn-dark btn-lg" href="{% url 'home' %}">Home</a>
	    <a role="button" class="p-2 btn btn-danger btn-lg" href="{% url 'login' %}">Login</a>
	    <a role="button" class="btn btn-light btn-outline-dark btn-lg" href="{% url 'register' %}">Register</a>
	{% endif %}	
    
  </nav>
</div>

<!-- End Header -->

<script type="text/javascript">
	document.getElementById("id_q").value = "{{query}}"
</script>

templates/register.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% load socialaccount %}
{% block content %}

<style type="text/css">
	.form-signin {
	width: 100%;
	max-width: 330px;
	padding: 15px;
	margin: 0 auto;
	}
	.form-signin .checkbox {
	font-weight: 400;
	}
	.form-signin .form-control {
	position: relative;
	box-sizing: border-box;
	height: auto;
	padding: 10px;
	font-size: 16px;
	}
	.form-signin .form-control:focus {
	z-index: 2;
	}
	.form-signin input[type="email"] {
	margin-bottom: 10px;
	border-bottom-right-radius: 0;
	border-bottom-left-radius: 0;
	}
	.form-signin input[type="text"] {
	margin-bottom: 10px;
	border-bottom-right-radius: 0;
	border-bottom-left-radius: 0;
	}
	.form-signin input[type="password"] {
	margin-bottom: -1px;
	border-top-left-radius: 0;
	border-top-right-radius: 0;
	}
	.h3{
		text-align: center;
	}
</style>

<form class="form-signin" method="post">{% csrf_token %}
	<div class="d-flex flex-column pb-3">
		<img class="img-fluid mx-auto d-block" src="https://i.ibb.co/s54bdnz/Elder-Aid-Logo-1.png" alt="Elder-Aid-Logo" width="72" height="72">
	</div>
	<h1 class="h3 mb-3 font-weight-normal">Register an account</h1>
	
	<label for="inputEmail" class="sr-only">Email address</label>
	<input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>

	<label for="inputUsername" class="sr-only">Username</label>
	<input type="text" name="username" id="inputUsername" class="form-control" placeholder="Username" required>

	<label for="inputName" class="sr-only">Name</label>
	<input type="text" name="name" id="inputName" class="form-control" placeholder="Name" required>
	
	<label for="inputPassword" class="sr-only">Password</label>
	<input type="password" name="password1" id="inputPassword1" class="form-control" placeholder="Password" required>

	<label for="inputPassword" class="sr-only">Confirm Password</label>
	<input type="password" name="password2" id="inputPassword2" class="form-control" placeholder="Confirm Password" required>

	<label for="inputPhone" class="sr-only">Phone Number</label>
	<input type="number" name="phone" id="inputPhone" class="form-control" placeholder="Phone Number" required>

	<label for="inputBirth" class="sr-only">Birthdate</label>
	<input type="date" name="birthdate" id="inputBirth" class="form-control" placeholder="Birthdate" required>

	{% for field in registration_form %}
		{% for error in field.errors %}
			<p style="color: red">{{ error }}</p>
		{% endfor %}
	{% endfor %}

	{% if registration_form.non_field_errors %}
		<div style="color:red "><p>{{ form.non_field_errors }}</p></div>
	{% endif %}
	<div class="d-flex justify-content-center">
		<button class="btn btn-lg btn-danger btn-block" type="submit">Register</button>
	</div>
	<div class="signin text-center m-auto mt-3">
		<a class="btn btn-outline-dark" href="{% provider_login_url 'google' %}" role="button" style="text-transform:none">
			<img width="20px" style="margin-bottom:3px; margin-right:5px" alt="Google sign-in" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png" />
			Login with Google
		</a>
	</div>
  </form>

<p class="text-center">
	If you already have an account, <a href="/login">login</a> instead.
</p>


{% endblock %}